version: "2" 
services:
  web:
    restart: always 
    ports:
     - "80:80"
    image: "arm32v7/php:7.2.2-apache-stretch"
    volumes:
     - "/home/pi/httpfiles/raspiwebserver/static:/var/www/html"
 
